kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    tags:
      - latest
      - build-${DRONE_BUILD_NUMBER}
    repo: tlemarchand/mumble
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: quay  
  image: plugins/docker
  settings:
    tags:
      - latest
      - build-${DRONE_BUILD_NUMBER}
    repo: quay.io/tlemarchand/mumble
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    registry: quay.io