kind: pipeline
name: default

steps:
- name: generate-versions
  image: debian:buster-slim
  commands:
  - apt-get update
  - "apt-cache policy mumble-server | sed -n -e 's/^.*Candidate: //p' | tr -d '\n' > version"

- name: set-tag-mumble
  image: debian:buster-slim
  commands:
  - APPVERSION=`cat version | cut -d~ -f 1 | cut -d+ -f 1`
  - echo $APPVERSION,latest,$APPVERSION-$DRONE_BUILD_NUMBER > .tags

# - name: docker  
#   image: plugins/docker
#   settings:
#     repo: tlemarchand/mumble
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password

- name: quay  
  image: plugins/docker
  settings:
    repo: quay.io/tlemarchand/mumble
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    registry: quay.io